namespace WinUI3cppWorkTest
{
    [default_interface]
    runtimeclass TaskSampleViewModel
    {
        TaskSampleViewModel(String name);
        String Name{ get; };
        Double ProgressPercent{ get; };
        Windows.UI.Color ProgressHighColor{ get; };
        Windows.UI.Color ProgressBaseColor{ get; };
        Microsoft.UI.Xaml.Visibility ProgressRowEffectVisibility{ get; };
        Microsoft.UI.Xaml.Visibility ProgressColumnEffectVisibility{ get; };
    }
}
