namespace WinUI3cppWorkTest
{
    [default_interface]
    runtimeclass TestControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        TestControl();

        Microsoft.UI.Xaml.Controls.Image ImageTest{ get; };
    }
}
